// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsjMFMw8IL-UH38QtDVNXwYD94OmzYlbQ',
    appId: '1:796969362138:android:1a4bd7f25e11830882fbe3',
    messagingSenderId: '796969362138',
    projectId: 'instantgram-80120',
    authDomain: 'instantgram-80120.firebaseapp.com',
    storageBucket: 'instantgram-80120.appspot.com',
    measurementId: 'G-7ZL2B4RGWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmI9r7wUom1ZyhOi5v0D1fR0ElZZEUVxE',
    appId: '1:796969362138:android:1a4bd7f25e11830882fbe3',
    messagingSenderId: '796969362138',
    projectId: 'instantgram-80120',
    storageBucket: 'instantgram-80120.appspot.com',
  );
}
